spring:
  application:
    name: state-finder-api
  webflux:
    base-path: /state-finder

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

data:
  shapefiles:
    us-states: classpath:data/us_states/cb_2018_us_state_500k.shp
